### ISSUE TITLE
Bug:banner images dont work properly when more than one

### ISSUE THREAD

**Issue by PTSdeveloper007** [trema-tech/moodle-theme_trema#188] opened 2024-05-02 03:47 UTC
### Prerequisites

- [X] I'm reporting the issue to the correct repository.
- [X] I am running the latest version of this plugin (if not, please upgrade first).
- [X] I checked the [README.md](../blob/master/README.md) and [Wiki](../wiki) documentation but did not find my answer.
- [X] I searched to make sure that this issue had not already been reported.
- [X] I have, or I know someone who has, the ability and willingness to test the fix on a Moodle LMS-based site.
- [X] I am submitting no more than one bug report per issue ticket (please do not submit multiple bugs in one issue ticket).
- [X] I understand that support is provided by volunteer(s).

### What happened?

How can i edit the banner slides on the frontpage please? and when you add more than one banner image, the image moves when scrolling down. any can help with this please ?
thanks

### What do you think should have happened?

the banner sliders to work correctly

### Steps to reproduce

1. Login as '...' (specify user role)
2. Go to '...'
3. Click on '....'
4. Scroll down to '....'
5. See error or issue.
You get it?

### Moodle version

Moodle 4.4.0

### Installed Moodle UI Language packs.

- [ ] English only
- [ ] One or more other languages/regional dialects (specify below)
- [ ] Other

### System information

Client Device type: (e.g. Desktop, iPhone or iPad, Android phone or tablet, Other - specify)
Client Operating System: (e.g. Windows, Linux, Mac OS, Android, iOS, Other - specify)
Client Web Browser: (e.g. Chrome, Edge, Firefox, Safari, Safe Exam Browser, Moodle Mobile App)
Server Operating System: (e.g. Windows, Linux, Mac OS, Other - specify)
Server Webserver: (e.g. Apache, Nginx, IIS, Other - specify)
Server PHP: (e.g. 7.4, 8.0, 8.1, 8.2, 8.3, Other - specify)

### Code of Conduct

- [X] I have read and agree to the project's <a href="../blob/master/CODE_OF_CONDUCT.md" target="_blank">code of conduct</a>.

**Comment by rmady** [comment] 2024-05-03 15:09
Hello @PTSdeveloper007,
Thank you for your contribution to Trema but I was unable to reproduce this bug. 
Please, can you send me a screenshot or a video of this issue?

Kind regards,
Rodrigo Mady

**Comment by PTSdeveloper007** [comment] 2024-05-06 02:51
![image](https://github.com/trema-tech/moodle-theme_trema/assets/49137695/94bd4bbb-fabd-485e-998d-44bf4ab9c3b9)

Hi, heres an image of issue. The banner slider doesnt stick to position but rather scrolls when you scroll down the page. This only happens when you add more than one image to the banner. 

It works well when there is only one image in banner. 

Thanks and hope to hear from you 

Peter

**Comment by PTSdeveloper007** [comment] 2024-05-06 03:25
This is another issue please 
![image](https://github.com/trema-tech/moodle-theme_trema/assets/49137695/1c411d82-18df-4049-98f6-a2fea2b32e80)

with the list buttons (attached) the padding within the buttons is uneven when hover/focus. 

Hope to hear from you

Peter

**Comment by PTSdeveloper007** [comment] 2024-05-06 03:31
more here 

![image](https://github.com/trema-tech/moodle-theme_trema/assets/49137695/1670e7be-dd5f-4ffd-b40c-3df4bcdf1947)

**Comment by michael-milette** [comment] 2024-05-07 00:55
Hi @PTSdeveloper007 

Thank you for the reports. We have been able to reproduce the issue with the carousel and are working on a solutions. Hopefully, we will have a fix this soon. 

As for the > not being centered, this should be fixed along with several other small issues in the experimental "dev" branch and will be included in the upcoming release shortly. Please feel free to try it out and let us know if it works for you. Note that you may need to change a theme setting (any one should do) in order for the css to recompile and take effect. This step will not be required in the released version.

In the future, we would appreciate it very much if you would kindly only include one issue per ticket as this helps us keep track of what has been fixed and what still needs attention - as indicated in the Prerequisite section of the ticket that you checked.

**Comment by rmady** [comment] 2024-05-10 00:05
Hello @PTSdeveloper007,
I just created a new version with these fixes. 
Please, check it out and let me know if everything is ok now.

Kind regards,
Rodrigo Mady

**Closed by rmady** 2024-05-10 00:05 UTC
Labels: bug

**Comment by PTSdeveloper007** [comment] 2024-05-12 20:57
This is working now thank you!
