### ISSUE TITLE
Padding Footer on Dashboard Page wrong size

### ISSUE THREAD

**Issue by alexjasoncrawl** [trema-tech/moodle-theme_trema#164] opened 2023-04-22 15:50 UTC
If you Logged in and you are on your Dashboard Page the Footer have the wrong size when the right sidebar is open. If the Sidebar is closed, the sizes is ok (see pic's)

Tested on
Trema version 4.1.0.0
Moodle Version: 4.1.2+ (Build: 20230418)
Diplay Res: 2560 width * 1440 height

![Screenshot 2023-04-22 at 17-37-25 Dashboard](https://user-images.githubusercontent.com/131540640/233794296-2708b90b-9125-4edf-af73-ebf821b6d3a0.png)
![Screenshot 2023-04-22 at 17-38-01 Dashboard](https://user-images.githubusercontent.com/131540640/233794297-1baaea20-2040-4d41-9d03-f102751f30d4.png)

**Comment by michael-milette** [comment] 2023-11-13 04:22
Hi @alexjasoncrawl ,

I just tried it on Moodle 4.3 with the latest version of Trema here on GitHub which was last updated on September 8 at the exact same resolution as you indicated. Unfortunately, I have been unable to reproduce the issue.

I understand that you are using Moodle 4.1 but could you please try it with the theme here on GitHub to see if that resolves the issue? Also, please try it with the Boost theme. The problem could possibly be with Moodle core.

Best regards,

Michael Milette

**Comment by alexjasoncrawl** [comment] 2023-11-13 11:02
Hi @michael-milette,

The Issue is on Trema Theme only (and only on Dashboard Site).



Using Moodle 4.3+ (Build: 20231110)
Trema 4.1.0.0 | 2023042100 | newest files installes Sept 8

**Comment by michael-milette** [comment] 2023-11-13 11:27
Hi @alexjasoncrawl ,

I understand. However, I have also tested it with Moodle 4.3+ with the same version of Trema that you are using yet I do not have the particular error that you indicated.
<img width="480" alt="image" src="https://github.com/trema-tech/moodle-theme_trema/assets/3808579/934e08fd-75b0-4ade-a841-7b744f51ee24">

Unless you can provide additional information, I will be unable to troubleshoot and help you any further.

Alternatively, please feel free to contact me through my website at https://www.tngconsulting.ca/contact if you would prefer to get premium support to troubleshoot the issue for you.

Best regards,

Michael Milette

**Comment by alexjasoncrawl** [comment] 2023-11-13 12:30
Hi @michael-milette 

Just to be on the safe side: It's about the footer area. When the right sidebar is closed, the padding values on the right are OK. If you open the right sidebar, there is a blank space between the footer and the sidebar (see first image, first post, red arrow).

Here the padding values are not correct in the CSS. And only on the dashboard page.

Greetings
Alex

**Comment by michael-milette** [comment] 2024-03-10 02:22
Hi @alexjasoncrawl ,

Which web browser are you using?

Also, are we looking at a course outline or inside a course activity?

Best regards,

Michael

**Comment by michael-milette** [comment] 2024-04-26 12:05
Hi @alexjasoncrawl ,

This should be fixed in the next release of Trema hopefully coming within the next few days. In the meantime, please feel free to test out our experimental dev branch which includes the fix.

Best regards,

Michael

**Closed by michael-milette** 2024-04-26 12:05 UTC
Labels: question
