### ISSUE TITLE
Moodle 4.2.1+ Dashboard Exception - Cannot access protected property core\check\result::$status

### ISSUE THREAD

**Issue by chrisacameron** [trema-tech/moodle-theme_trema#168] opened 2023-07-05 21:48 UTC
Using Trema v 4.1.0.0 (2023042100), and after upgrading to Moodle 4.2.1+ (20230616), we are seeing the following error:

`Error - Exception - Cannot access protected property core\check\result::$status`

Other users also reporting the issue in comments at: https://moodle.org/plugins/theme_trema
- [Andrew Lian] Sun, Jun 25, 2023, 2:43 AM
- [Fabio R L] Wed, Jun 28, 2023, 3:37 AM

Workaround:
**Site Administration > Appearance > Navigation** : set Enable Dashboard (**enabledashboard**) to **No**
OR
**Site Administration > Appearance > Navigation** : set Start page for users (**defaulthomepage**) to **something besides Dashboard** (but the Error will still be generated if user clicks on Dashboard link in top navigation)

**Comment by markginter31** [comment] 2023-08-06 19:01
I have this same bug.

**Comment by BK787** [comment] 2023-08-12 22:26
Likewise.

**Comment by cpaschen** [comment] 2023-09-04 18:37
same here also

**Comment by michael-milette** [comment] 2023-11-13 03:19
Using the version from Sept 8, I am no longer able to reproduce the issue. Thank you for fixing this @rmady !

**Comment by alexjasoncrawl** [comment] 2023-11-13 10:16
Hey @michael-milette,
Hey @rmady 

The Dashboard Exception (Cannot access protected property core\check\result::$status) isnt fixed for 
Moodle 4.3+ (Build 20231110)
Trema V4.1.0.0 2023042100

Please reopen the Issue.

Greeting AleJasonCrawl

**Comment by michael-milette** [comment] 2023-11-13 10:53
Hi @alexjasoncrawl ,

I am still unable to reproduce your issue. I would appreciate it if you could provide me with additional information.

As a Site Administrator, could you please navigate to **Site Administration > Development** and set **Debug Messages** to **DEVELOPER: extra Moodle debug messages for developers**. Also, make sure that the box to **Display debug messages** is checked. Save your changes and then do whatever you do to cause the error.

You should end up seeing more than just the **Cannot access protected property core\check\result::$status** message.

Please copy and paste the additional information back here. Don't forget to go back and set Debugging Messages to NONE.

Also, please describe any blocks or customized settings you might have as the problem may only be manifesting itself when the configuration is a certain way. My Moodle 4.3 test installation is pretty basic with very few custom settings. Any information that might help me re-create the problem would be most helpful.

Best regards,

Michael

**Comment by snack753** [comment] 2023-11-13 12:59
Hi Michael,
I am afraid I will not be able to provide you with more details, since we decided to update to a compatible/older version of Moodle.
Sorry, Kai

**Comment by michael-milette** [comment] 2023-11-15 07:48
No problem Kai. Thanks for letting us know.

@markginter31 @chrisacameron @BK787 @cpaschen @alexjasoncrawl , can any of you help me track down this issue? Please try version 4.3.0.0 which was recently released (Nov 14). Specifically, if you can still reproduce the issue, please try it with the Trema Admin Dashboard enabled and disabled, and let me know if it makes a difference.

Best regards,

Michael
<img width="400" alt="image" src="https://github.com/trema-tech/moodle-theme_trema/assets/3808579/7e18375b-80f3-46d1-8335-196767e589e7">

I just found a bug but the error does not match the one reported in this ticket.

Best regards,

Michael

**Comment by snack753** [comment] 2023-11-15 12:41
Hi Michael,
I remembered that I still have access to V4.2.1 with Trema installed.
The debug result shows this:
Error
Exception - Cannot access protected property core\check\result::$status
Debug info:
Error code: generalexceptionmessage
Stack trace:
line 194 of /theme/trema/locallib.php: Error thrown
line 100 of /theme/trema/layout/mydashboard.php: call to theme_trema_get_environment_issues()
line 1477 of /lib/outputrenderers.php: call to include()
line 1403 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
line 179 of /my/index.php: call to core_renderer->header()

Hope this helps

**Comment by snack753** [comment] 2023-11-16 16:02
PS: regarding the blocks on my dashboard. I have these blocks activated currently:
- Advanced notifications
- Course Overview
- Timeline
- Calendar
- Recently accessed items

That's it. Nothing fancy

**Comment by chrisacameron** [comment] 2023-11-16 16:45
> No problem Kai. Thanks for letting us know.
> 
> @markginter31 @chrisacameron @BK787 @cpaschen @alexjasoncrawl , can any of you help me track down this issue? Please try version 4.3.0.0 which was recently released (Nov 14). Specifically, if you can still reproduce the issue, please try it with the Trema Admin Dashboard enabled and disabled, and let me know if it makes a difference.
> 
> <img alt="image" width="400" src="https://user-images.githubusercontent.com/3808579/283040937-7e18375b-80f3-46d1-8335-196767e589e7.png">
> I just found a bug but the error does not match the one reported in this ticket.
> 
> Best regards,
> 
> Michael

Still an issue with Moodle v4.3+ Build: 20231110 and Trema 4.1.0.0
Upgraded Trema to 4.3.0.0 and no longer an issue

**Comment by michael-milette** [comment] 2023-11-16 17:21
Hi @chrisacameron ,

Thank you for getting back to me. Good to know that the issue has been resolved in v4.3.0.0. I will close this ticket.

If anyone else is able to reproduce the issue with v4.3.0.0 in Moodle 4.1, 4.2 or 4.3, please post details and I will reopen this ticket.

Best regards,

Michael Milette

**Comment by michael-milette** [comment] 2023-11-16 17:25
@snack753 ,

Can you please confirm whether this is still an issue on Moodle 4.2.1 with Trema v4.3.0.0?

Michael

**Comment by rmady** [comment] 2023-11-22 15:03
Looks like everything is all right now.
Please, let me know if this issue is happening with someone else.
Thank  you very much guys

**Closed by rmady** 2023-11-22 15:03 UTC
