### ISSUE TITLE
Blanck Screen with non-existent user

### ISSUE THREAD

**Issue by jbelardosales** [trema-tech/moodle-theme_trema#161] opened 2023-03-07 19:24 UTC
Hi guys, i have a problem on the login screen

When entering the login screen with a non-existent user, it presents a blank screen, and only after I refresh the url does the login screen appear again. This problem only occurs with unregistered users. If the password is wrong, it refreshes the login screen normally. Does anyone know how to fix this in code?

[BLANK SCREEN - NOT REFRESH URL TO RELOAD THE LOGIN PAGE AGAIN.pdf](https://github.com/trema-tech/moodle-theme_trema/files/10913234/BLANK.SCREEN.-.NOT.REFRESH.URL.TO.RELOAD.THE.LOGIN.PAGE.AGAIN.pdf)
[LOGIN SCREEN USER NON-EXISTENT.pdf](https://github.com/trema-tech/moodle-theme_trema/files/10913236/LOGIN.SCREEN.USER.NON-EXISTENT.pdf)

**Comment by michael-milette** [comment] 2023-11-13 06:24
Hi @jbelardosales ,

I cannot reproduce this issue. What version of Moodle LMS and what version of the theme are you using?

Best regards,

Michael

**Comment by michael-milette** [comment] 2024-03-28 16:53
There has been no further discussion in the past 4 months regarding this ticket. I am closing this ticket. If you are still experiencing this issue, please feel free to re-open this ticket or create a new one.

Best regards,

Michael

**Closed by michael-milette** 2024-03-28 16:53 UTC
Labels: question
