### ISSUE TITLE
Bug: suspended (error ID '2')

### ISSUE THREAD

**Issue by salman99222** [trema-tech/moodle-theme_trema#192] opened 2024-05-19 09:20 UTC
### Prerequisites

- [X] I'm reporting the issue to the correct repository.
- [X] I am running the latest version of this plugin (if not, please upgrade first).
- [X] I checked the [README.md](../blob/master/README.md) and [Wiki](../wiki) documentation but did not find my answer.
- [X] I searched to make sure that this issue had not already been reported.
- [ ] I have, or I know someone who has, the ability and willingness to test the fix on a Moodle LMS-based site.
- [X] I am submitting no more than one bug report per issue ticket (please do not submit multiple bugs in one issue ticket).
- [X] I understand that support is provided by volunteer(s).

### What happened?

Hello,,, After installing the Terma theme, many users saw their account suspended and I don’t know why!  Version 4.3.3

### What do you think should have happened?

I expected 'Hello,,, After installing the Terma theme, many users saw their account suspended and I don’t know why!  Version 4.3.3'

### Steps to reproduce

1. Login as '...' (specify user role)
2. Go to '...'
3. Click on '....'
4. Scroll down to '....'
5. See error or issue.
You get it?

### Moodle version

4.3.3

### Installed Moodle UI Language packs.

- [ ] English only
- [X] One or more other languages/regional dialects (specify below)
- [ ] Other

### Workaround

No

### System information

Client Device type: (e.g. Desktop, iPhone or iPad, Android phone or tablet, Other - specify)
Client Operating System: (e.g. Windows, Linux, Mac OS, Android, iOS, Other - specify)
Client Web Browser: (e.g. Chrome, Edge, Firefox, Safari, Safe Exam Browser, Moodle Mobile App)
Server Operating System: (e.g. Windows, Linux, Mac OS, Other - specify)
Server Webserver: (e.g. Apache, Nginx, IIS, Other - specify)
Server PHP: (e.g. 7.4, 8.0, 8.1, 8.2, 8.3, Other - specify)

### Code of Conduct

- [X] I have read and agree to the project's <a href="../blob/master/CODE_OF_CONDUCT.md" target="_blank">code of conduct</a>.

**Comment by michael-milette** [comment] 2024-05-19 17:09
Hi @salman99222 , 

There is nothing in Trema that could cause a user account to be suspended. 

Are you sure that installing Trema was the only change you made to your Moodle site? Based on the little information you provided, my guess is that you may have also recently upgraded your version of Moodle to version 4.3.3 (there was never a Trema version 4.3.3).

<img width="229" alt="image" src="https://github.com/trema-tech/moodle-theme_trema/assets/3808579/4555226e-580f-4eed-b8bb-75212591aec2">

Hopefully, you also made sure that your server environment meets the Moodle 4.3.3 system requirements, that you made sure that all of your third-party plugins were compatible with Moodle 4.3.3 and that you upgraded any that were not. I am also surprised that this issue did not come up when you tested the upgrade in your sandbox environment before upgrading your production environment.

Bulk suspension of users like this would have been performed by a scheduled task, which Trema doesn't have any. This type of issue is usually related to authentication, not a Moodle theme. Perhaps you did something else that fixed or caused a bug in a scheduled task. Or perhaps someone fixed the cron job and it is now processing a backlog of tasks like suspending users. 

You might want to take a look at your Moodle and server logs to see if you can figure out exactly what happened.

To fix your issue, you should be able to restore the backup of your database, from before the upgrade, into a new database (do not replace your production database) and use SQL to get the suspension status of all your users before the upgrade. Once you have exported that information, you can then import it into your production site thereby restoring the suspension status of all your users.

IMPORTANT: However, until you figure out the actual reason they became suspended in the first place and fix the issue, it is very likely that something will simply suspend their accounts again.

I hope you found this information helpful.

I am closing this ticket as the issue is unrelated to the Trema theme.

Best regards,

Michael Milette

**Closed by michael-milette** 2024-05-19 17:09 UTC
