### ISSUE TITLE
Moodle 4.1.6 Drawer Block issue

### ISSUE THREAD

**Issue by gioconte2** [trema-tech/moodle-theme_trema#172] opened 2023-10-31 13:47 UTC
Hello, I have upgraded to moodle version 4.1.6, and used the lastest version of the Trema theme. But, after going to the Dashboard as soosn as I click to open the drawer I am getting the following error: "Error updating user preference 'drawer-open-block' using ajax. Clicking this link will repeat the Ajax call that failed so you can see the error: " as warning pop up window. But, after clicking on the "Ok" button of the button pop up window, it does not apper anymore. The problem is everytime I log back into it, and go to the Dashboard and open the drawer the error message appears again. Could someone have a look at it, and try to fix the issue, becaue we really like the Trema theme and would like to keep on using it. This is the error I see when I look at the inspect console: "Failed to load resource: the server responded with a status of 404 (Not Found)
/lib/ajax/setuserpref.php?sesskey=heUrxjEJuN&pref=drawer-open-block&value=true". FYI, I did I test by selecting the Boost theme insetad of Trema, and when I do the above mentioned steps I do not get the error. Thank you. Giovanni.

**Comment by michael-milette** [comment] 2023-11-08 22:23
Hi @rmady ,

I have the same issue when I open the drawer on the home page when I am logged out and have never opened the drawer.

This can be reproduced by opening an Incognito/Private window in your web browser, navigating to the home page and opening the blocks drawer.
<img width="287" alt="image" src="https://github.com/trema-tech/moodle-theme_trema/assets/3808579/59f45308-6839-426f-a375-852a45a6730b">

Note that this **only happens the first time** you open the block drawer (or after you delete the cookie I suppose). Does not seem to matter whether you are logged in or out.

Best regards,

Michael Milette

**Comment by michael-milette** [comment] 2023-11-11 09:48
Note that I cannot reproduce the issue anymore using the latest main branch of Trema available here on GitHub from September 8, 2023 on Moodle 4.3.

Michael

**Comment by ewallah** [comment] 2023-11-18 18:45
In Moodle 4.3 the error (but perhaps also the functionality) is gone due to [line 34](https://github.com/trema-tech/moodle-theme_trema/blob/main/layout/drawers.php#L34C1-L34C27) `if ($CFG->branch <= 402) {`

The easiest way to check or reproduce this problem is using [Behat](https://moodledev.io/general/development/tools/behat/running):

`php admin/tool/behat/cli/run.php --profile="chrome" --tags="@block_navigation" --suite="trema"`

**Comment by michael-milette** [comment] 2023-11-19 16:58
Hi @ewallah ,

Thanks for the feedback. However, that fix was only introduced a few days ago and only affects Moodle 4.3+. The original report was an issue with 4.1.

As for the functionality, I noticed a similar change in all Boost-based themes for 4.3. Those lines are usually removed but I used this IF statement to maintain compatibility with previous versions of Moodle.

In any case, I am going to close this ticket as done since nobody seems to be able to reproduce the issue anymore. Should someone be able to reproduce the issue, please add a comment and I will reopen this ticket.

Thanks again for taking the time to test, report back and the behat tip.

Best regards,

Michael

**Closed** 2023-11-19 16:59 UTC
