### ISSUE TITLE
Bug: Category pills rendering black

### ISSUE THREAD

**Issue by SollalF** [trema-tech/moodle-theme_trema#199] opened 2024-09-25 01:42 UTC
### Prerequisites

- [X] I'm reporting the issue to the correct repository.
- [X] I am running the latest version of this plugin (if not, please upgrade first).
- [X] I checked the [README.md](../blob/master/README.md) and [Wiki](../wiki) documentation but did not find my answer.
- [X] I searched to make sure that this issue had not already been reported.
- [ ] I have, or I know someone who has, the ability and willingness to test the fix on a Moodle LMS-based site.
- [X] I am submitting no more than one bug report per issue ticket (please do not submit multiple bugs in one issue ticket).
- [X] I understand that support is provided by volunteer(s).

### What happened?

With the basic settings, under site administration>courses>add a category the pill to show the parent category displays a dark text on a dark background.

### What do you think should have happened?

I expected the button to be readable. My settings are all reset to default so I don't think it is a fault of configuration. The element has a bg-secondary applied on it but changing the secondary color does not seem to affect it.

### Steps to reproduce

1. Login as admin (specify user role)
2. Go to administration>courses>add a category
3. Scroll down to "Add new category"
4. See error or issue.

### Screenshots

<img width="252" alt="image" src="https://github.com/user-attachments/assets/a7089d6e-f471-455e-a0ee-fe8b0efdc306">

### Moodle version

4.4.3

### Installed Moodle UI Language packs.

- [X] English only
- [ ] One or more other languages/regional dialects (specify below)
- [ ] Other

### System information

Client Device type: (e.g. Desktop, iPhone or iPad, Android phone or tablet, Other - specify)
Client Operating System: (e.g. Windows, Linux, Mac OS, Android, iOS, Other - specify)
Client Web Browser: (e.g. Chrome, Edge, Firefox, Safari, Safe Exam Browser, Moodle Mobile App)
Server Operating System: (e.g. Windows, Linux, Mac OS, Other - specify)
Server Webserver: (e.g. Apache, Nginx, IIS, Other - specify)
Server PHP: (e.g. 7.4, 8.0, 8.1, 8.2, 8.3, Other - specify)

### Code of Conduct

- [X] I have read and agree to the project's <a href="../blob/master/CODE_OF_CONDUCT.md" target="_blank">code of conduct</a>.

**Comment by michael-milette** [comment] 2024-09-25 14:28
Hi @SollalF ,

Thank you for taking the time to report this issue. I believe the problem you described was addressed as a result of issue #198 and included in the Trema 4.4.0.7 release a couple of weeks ago. 

Please try upgrading to the most recent release of Trema. If this does not address your issue, please confirm the version of Trema that you are using and provide us with the following Trema settings:

- Primary color:
- Secondary color:
- Body background color:
- Header Background color:
- Drawer Background color:
- Footer Background color:

Best regards,

Michael Milette

**Comment by michael-milette** [comment] 2024-09-25 14:33
Ignore my last message. I just figured out how to reproduce the issue. Will get back to you as soon as I have fixed the issue.

**Comment by michael-milette** [comment] 2024-09-25 15:42
HI @SollalF ,

Could you please try the version of Trema here on GitHub? Specifically, the "**dev**" branch. Let me know whether this works for you or not. If it does, this fix will be included in the next release of Trema on Moodle.org.

Best regards,

Michael

**Comment by michael-milette** [comment] 2024-10-03 22:08
I've checked this now on multiple Moodle 4.4 installations and it seems to be fixed everywhere. Closing this ticker as done.

Best regards,

Michael

**Closed by michael-milette** 2024-10-03 22:08 UTC
