### ISSUE TITLE
Site Admin search form and Site Administration width is not applied (SOLUTION INCLUDED)

### ISSUE THREAD

**Issue by git4ths** [trema-tech/moodle-theme_trema#140] opened 2022-08-26 04:01 UTC
Hi Team,

First of all, I really love the theme so congratulations! I am a bit of perfectionist and I want everything in order. I noticed that the Search form and Site administration are near to each other. You'll see the problem below

![image](https://user-images.githubusercontent.com/112147335/186814328-8796eebb-d389-4b1c-9767-738ce12e9b32.png)

This is the correct one though, but it is on another page

![image](https://user-images.githubusercontent.com/112147335/186815757-8eca8d76-001c-4dc8-a6b1-70a5d9d6bc09.png)

**Comment by michael-milette** [comment] 2022-08-26 05:19
Hi @git4ths ,

I am not sure I follow what you are trying to explain. Could you perhaps try again and include the steps to reproduce the issue?

Best regards,

Michael

**Comment by git4ths** [comment] 2022-08-26 09:58
Sorry, for the vague report.

If you click Site Administration via the Navigation bar at the top. You will notice that the search form was close to the Heading "Site Administration" as you will see at the picture below:

![image](https://user-images.githubusercontent.com/112147335/186877689-f7efd996-30bb-4bf4-8b68-6f810c4e1f26.png)


But if you go to "Site Administration > Appearance > Themes (Trema)." You will see on the screenshot below, the correct spacing of the Heading and the search form. I tried switching it to the Boost preset, and was able to confirm that they should be far from each other like on the screenshot below.

![image](https://user-images.githubusercontent.com/112147335/186878652-cbdab1f2-88b1-4f23-b6e2-265b8bd2f885.png)


If the Site Administration and search form are intentionally setup that way, that's fine. However, any code to set them apart would be really helpful, thanks!

**Comment by michael-milette** [comment] 2022-08-27 05:33
Hi @git4ths ,

Thank you for the improved report. I see it now. It is shifted to the left (not centered) and missing space in between.

Michael

**Comment by michael-milette** [comment] 2022-09-06 15:57
HI @git4ths ,

Here is a temporary workaround until the issue is fixed in Trema. Just add the following to the theme's SCSS:

    // Temporary fix for Trema issue number 140.
    #page-admin-search #page-header .mr-auto {
        margin-right: auto!important;
    }
    #page-admin-search #page-header {
        margin: 0 auto;
    }

Best regards,

Michael Milette

**Comment by michael-milette** [comment] 2023-11-13 07:51
Hi @rmady ,

Please test and integrate PR #180. Thanks!

Best regards,

Michael Milette

**Comment by rmady** [comment] 2023-11-14 22:37
Thanks guys @git4ths and @michael-milette! 
I'm working on the new release and this PR will be fixed over there. For instance, it is in the main branch.

Kind regards,
Rodrigo Mady

**Closed by rmady** 2023-11-14 22:37 UTC
Labels: bug, Test it!
