### ISSUE TITLE
error rendering course summary page

### ISSUE THREAD

**Issue by shides-ac** [trema-tech/moodle-theme_trema#37] opened 2021-06-07 13:36 UTC
Hello, 
I've updated Moodle to the latest version (3.11) and I've an issue in rendering the course page.
The error disappear in editing mode.

Error:
![image](https://user-images.githubusercontent.com/17979618/121025893-edea0400-c7a5-11eb-830d-8867246075f2.png)
Editing mode:
![image](https://user-images.githubusercontent.com/17979618/121026064-1245e080-c7a6-11eb-8af6-8885888c4d52.png)

**Comment by rmady** [comment] 2021-06-09 14:29
Hi there @shides-ac, 

I just release a new version of trema and add settings to enable the new format topics. 

In editing mode I just don't want to show the new style, but the new style is not working well in your Moodle. 

Must be something like this:
![Captura de tela de 2021-06-09 11-13-02](https://user-images.githubusercontent.com/8494871/121373825-c619ae00-c915-11eb-9569-03a815632186.png)

When you access with students the layout still broken? Can yout test for me in this new release?

**Comment by shides-ac** [comment] 2021-06-15 10:38
Hi @rmady 

thank you for your reply, unfortunately I cannot test anymore the theme on Moodle 3.11 because I roll back to the previous version and then installed the LTS. 
I'll do my best to test it into a local installation and let you know.

Thank you.

**Comment by michael-milette** [comment] 2021-12-29 10:30
I tested this in Moodle 3.11 with the latest release of Trema. It works as you described however I think that the appearance should be consistent (not change) regardless of whether or not editing is on or off.

**Comment by michael-milette** [comment] 2021-12-29 10:55
The summary content should be aligned with the top, not the bottom. To reproduce this, add several activities in the section but only one word in the section summary.

**Comment by michael-milette** [comment] 2024-05-16 05:16
Support for the modifications to course layouts called "Enable Trema Course Style for Topics" was deprecated with the release of Moodle 4.0. Since then, the settings has only affected the padding around the content. It has therefore been removed in the experimental dev branch and will no longer be available in future releases. Closing this issue as it is no longer relevant.

Best regards,

Michael

**Closed by michael-milette** 2024-05-16 05:16 UTC
Labels: bug
